<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-01T16:48:55Z" name="Suite" finished-at="2024-04-01T16:49:04Z" duration-ms="8876">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidationTest()[pri:0, instance:mylearnings.tests.ErrorValidationTest@6293abcc]" name="loginErrorValidationTest" class="mylearnings.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-04-01T16:48:55Z" name="EndtoEndTest" finished-at="2024-04-01T16:48:55Z" duration-ms="2">
    </test> <!-- EndtoEndTest -->
    <test started-at="2024-04-01T16:48:55Z" name="ErrorValidations" finished-at="2024-04-01T16:49:04Z" duration-ms="8828">
      <class name="mylearnings.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplicationPage()[pri:0, instance:mylearnings.tests.ErrorValidationTest@6293abcc]" started-at="2024-04-01T16:48:55Z" name="launchApplicationPage" finished-at="2024-04-01T16:49:03Z" duration-ms="7759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplicationPage -->
        <test-method signature="loginErrorValidationTest()[pri:0, instance:mylearnings.tests.ErrorValidationTest@6293abcc]" started-at="2024-04-01T16:49:03Z" name="loginErrorValidationTest" finished-at="2024-04-01T16:49:04Z" duration-ms="911" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at mylearnings.tests.ErrorValidationTest.loginErrorValidationTest(ErrorValidationTest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidationTest -->
        <test-method is-config="true" signature="closeApplication()[pri:0, instance:mylearnings.tests.ErrorValidationTest@6293abcc]" started-at="2024-04-01T16:49:04Z" name="closeApplication" finished-at="2024-04-01T16:49:04Z" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- mylearnings.tests.ErrorValidationTest -->
    </test> <!-- ErrorValidations -->
  </suite> <!-- Suite -->
</testng-results>
